function removeForms(){
  document.getElementById('updateSex').style.display="none";
  document.getElementById('insertSex').style.display="none";
  document.getElementById('deleteSex').style.display="none";
  document.getElementById('insertCountry').style.display="none";
  document.getElementById('updateCountry').style.display="none";
  document.getElementById('deleteCountry').style.display="none";
  document.getElementById('insertCity').style.display="none";
  document.getElementById('updateCity').style.display="none";
  document.getElementById('deleteCity').style.display="none";
  document.getElementById('insertAddress').style.display="none";
  document.getElementById('updateAddress').style.display="none";
  document.getElementById('deleteAddress').style.display="none";
  document.getElementById('insertContact').style.display="none";
  document.getElementById('updateContact').style.display="none";
  document.getElementById('deleteContact').style.display="none";
  
}
function addNewSex(){
  document.getElementById('updateSex').style.display="none";
  document.getElementById('insertSex').style.display="initial";
  document.getElementById('deleteSex').style.display="none";
    document.getElementById('insertCountry').style.display="none";
    document.getElementById('updateCountry').style.display="none";
    document.getElementById('deleteCountry').style.display="none";
    document.getElementById('insertCity').style.display="none";
      document.getElementById('updateCity').style.display="none";
        document.getElementById('deleteCity').style.display="none";
        document.getElementById('insertAddress').style.display="none";
        document.getElementById('updateAddress').style.display="none";
        document.getElementById('deleteAddress').style.display="none";
          document.getElementById('insertContact').style.display="none";
            document.getElementById('updateContact').style.display="none";
            document.getElementById('deleteContact').style.display="none";
}
function updateSex(){
  document.getElementById('updateSex').style.display="initial";
  document.getElementById('insertSex').style.display="none";
  document.getElementById('deleteSex').style.display="none";
  document.getElementById('insertCountry').style.display="none";
  document.getElementById('updateCountry').style.display="none";
  document.getElementById('deleteCountry').style.display="none";
  document.getElementById('insertCity').style.display="none";
    document.getElementById('updateCity').style.display="none";
      document.getElementById('deleteCity').style.display="none";
      document.getElementById('insertAddress').style.display="none";
      document.getElementById('updateAddress').style.display="none";
      document.getElementById('deleteAddress').style.display="none";
        document.getElementById('insertContact').style.display="none";
          document.getElementById('updateContact').style.display="none";
          document.getElementById('deleteContact').style.display="none";
}
function deleteSex(){
  document.getElementById('updateSex').style.display="none";
  document.getElementById('insertSex').style.display="none";
  document.getElementById('deleteSex').style.display="initial";
  document.getElementById('insertCountry').style.display="none";
  document.getElementById('updateCountry').style.display="none";
  document.getElementById('deleteCountry').style.display="none";
  document.getElementById('insertCity').style.display="none";
    document.getElementById('updateCity').style.display="none";
      document.getElementById('deleteCity').style.display="none";
      document.getElementById('insertAddress').style.display="none";
      document.getElementById('updateAddress').style.display="none";
      document.getElementById('deleteAddress').style.display="none";
        document.getElementById('insertContact').style.display="none";
          document.getElementById('updateContact').style.display="none";
          document.getElementById('deleteContact').style.display="none";
}
function insertCountry(){
  document.getElementById('updateSex').style.display="none";
  document.getElementById('insertSex').style.display="none";
  document.getElementById('deleteSex').style.display="none";
  document.getElementById('insertCountry').style.display="initial";
  document.getElementById('updateCountry').style.display="none";
  document.getElementById('deleteCountry').style.display="none";
  document.getElementById('insertCity').style.display="none";
    document.getElementById('updateCity').style.display="none";
      document.getElementById('deleteCity').style.display="none";
      document.getElementById('insertAddress').style.display="none";
      document.getElementById('updateAddress').style.display="none";
      document.getElementById('deleteAddress').style.display="none";
        document.getElementById('insertContact').style.display="none";
          document.getElementById('updateContact').style.display="none";
          document.getElementById('deleteContact').style.display="none";
}
function updateCountry(){
  document.getElementById('updateSex').style.display="none";
  document.getElementById('insertSex').style.display="none";
  document.getElementById('deleteSex').style.display="none";
  document.getElementById('insertCountry').style.display="none";
  document.getElementById('updateCountry').style.display="initial";
  document.getElementById('deleteCountry').style.display="none";
  document.getElementById('insertCity').style.display="none";
    document.getElementById('updateCity').style.display="none";
      document.getElementById('deleteCity').style.display="none";
      document.getElementById('insertAddress').style.display="none";
      document.getElementById('updateAddress').style.display="none";
      document.getElementById('deleteAddress').style.display="none";
        document.getElementById('insertContact').style.display="none";
          document.getElementById('updateContact').style.display="none";
          document.getElementById('deleteContact').style.display="none";
}
function deleteCountry(){
  document.getElementById('updateSex').style.display="none";
  document.getElementById('insertSex').style.display="none";
  document.getElementById('deleteSex').style.display="none";
  document.getElementById('insertCountry').style.display="none";
  document.getElementById('updateCountry').style.display="none";
  document.getElementById('deleteCountry').style.display="initial";
  document.getElementById('insertCity').style.display="none";
    document.getElementById('updateCity').style.display="none";
      document.getElementById('deleteCity').style.display="none";
      document.getElementById('insertAddress').style.display="none";
      document.getElementById('updateAddress').style.display="none";
      document.getElementById('deleteAddress').style.display="none";
        document.getElementById('insertContact').style.display="none";
          document.getElementById('updateContact').style.display="none";
          document.getElementById('deleteContact').style.display="none";
}
function insertCity(){
  document.getElementById('updateSex').style.display="none";
  document.getElementById('insertSex').style.display="none";
  document.getElementById('deleteSex').style.display="none";
  document.getElementById('insertCountry').style.display="none";
  document.getElementById('updateCountry').style.display="none";
  document.getElementById('deleteCountry').style.display="none";
  document.getElementById('insertCity').style.display="initial";
  document.getElementById('updateCity').style.display="none";
    document.getElementById('deleteCity').style.display="none";
    document.getElementById('insertAddress').style.display="none";
    document.getElementById('updateAddress').style.display="none";
    document.getElementById('deleteAddress').style.display="none";
      document.getElementById('insertContact').style.display="none";
        document.getElementById('updateContact').style.display="none";
        document.getElementById('deleteContact').style.display="none";
}
function updateCity(){
  document.getElementById('updateSex').style.display="none";
  document.getElementById('insertSex').style.display="none";
  document.getElementById('deleteSex').style.display="none";
  document.getElementById('insertCountry').style.display="none";
  document.getElementById('updateCountry').style.display="none";
  document.getElementById('deleteCountry').style.display="none";
  document.getElementById('insertCity').style.display="none";
  document.getElementById('updateCity').style.display="initial";
  document.getElementById('deleteCity').style.display="none";
  document.getElementById('insertAddress').style.display="none";
  document.getElementById('updateAddress').style.display="none";
  document.getElementById('deleteAddress').style.display="none";
    document.getElementById('insertContact').style.display="none";
      document.getElementById('updateContact').style.display="none";
      document.getElementById('deleteContact').style.display="none";
}
function deleteCity(){
  document.getElementById('updateSex').style.display="none";
  document.getElementById('insertSex').style.display="none";
  document.getElementById('deleteSex').style.display="none";
  document.getElementById('insertCountry').style.display="none";
  document.getElementById('updateCountry').style.display="none";
  document.getElementById('deleteCountry').style.display="none";
  document.getElementById('insertCity').style.display="none";
  document.getElementById('updateCity').style.display="none";
  document.getElementById('deleteCity').style.display="initial";
  document.getElementById('insertAddress').style.display="none";
  document.getElementById('updateAddress').style.display="none";
  document.getElementById('deleteAddress').style.display="none";
    document.getElementById('insertContact').style.display="none";
      document.getElementById('updateContact').style.display="none";
      document.getElementById('deleteContact').style.display="none";
}
function insertAddress(){
  document.getElementById('updateSex').style.display="none";
  document.getElementById('insertSex').style.display="none";
  document.getElementById('deleteSex').style.display="none";
  document.getElementById('insertCountry').style.display="none";
  document.getElementById('updateCountry').style.display="none";
  document.getElementById('deleteCountry').style.display="none";
  document.getElementById('insertCity').style.display="none";
  document.getElementById('updateCity').style.display="none";
  document.getElementById('deleteCity').style.display="none";
  document.getElementById('insertAddress').style.display="initial";
  document.getElementById('updateAddress').style.display="none";
  document.getElementById('deleteAddress').style.display="none";
    document.getElementById('insertContact').style.display="none";
      document.getElementById('updateContact').style.display="none";
      document.getElementById('deleteContact').style.display="none";
}
function updateAddress(){
  document.getElementById('updateSex').style.display="none";
  document.getElementById('insertSex').style.display="none";
  document.getElementById('deleteSex').style.display="none";
  document.getElementById('insertCountry').style.display="none";
  document.getElementById('updateCountry').style.display="none";
  document.getElementById('deleteCountry').style.display="none";
  document.getElementById('insertCity').style.display="none";
  document.getElementById('updateCity').style.display="none";
  document.getElementById('deleteCity').style.display="none";
  document.getElementById('insertAddress').style.display="none";
  document.getElementById('updateAddress').style.display="initial";
  document.getElementById('deleteAddress').style.display="none";
    document.getElementById('insertContact').style.display="none";
      document.getElementById('updateContact').style.display="none";
      document.getElementById('deleteContact').style.display="none";
}
function deleteAddress(){
  document.getElementById('updateSex').style.display="none";
  document.getElementById('insertSex').style.display="none";
  document.getElementById('deleteSex').style.display="none";
  document.getElementById('insertCountry').style.display="none";
  document.getElementById('updateCountry').style.display="none";
  document.getElementById('deleteCountry').style.display="none";
  document.getElementById('insertCity').style.display="none";
  document.getElementById('updateCity').style.display="none";
  document.getElementById('deleteCity').style.display="none";
  document.getElementById('insertAddress').style.display="none";
  document.getElementById('updateAddress').style.display="none";
  document.getElementById('deleteAddress').style.display="initial";
    document.getElementById('insertContact').style.display="none";
      document.getElementById('updateContact').style.display="none";
      document.getElementById('deleteContact').style.display="none";
}
function insertContact(){
  document.getElementById('updateSex').style.display="none";
  document.getElementById('insertSex').style.display="none";
  document.getElementById('deleteSex').style.display="none";
  document.getElementById('insertCountry').style.display="none";
  document.getElementById('updateCountry').style.display="none";
  document.getElementById('deleteCountry').style.display="none";
  document.getElementById('insertCity').style.display="none";
  document.getElementById('updateCity').style.display="none";
  document.getElementById('deleteCity').style.display="none";
  document.getElementById('insertAddress').style.display="none";
  document.getElementById('updateAddress').style.display="none";
  document.getElementById('deleteAddress').style.display="none";
    document.getElementById('insertContact').style.display="initial";
      document.getElementById('updateContact').style.display="none";
      document.getElementById('deleteContact').style.display="none";
}
function updateContact(){
  document.getElementById('updateSex').style.display="none";
  document.getElementById('insertSex').style.display="none";
  document.getElementById('deleteSex').style.display="none";
  document.getElementById('insertCountry').style.display="none";
  document.getElementById('updateCountry').style.display="none";
  document.getElementById('deleteCountry').style.display="none";
  document.getElementById('insertCity').style.display="none";
  document.getElementById('updateCity').style.display="none";
  document.getElementById('deleteCity').style.display="none";
  document.getElementById('insertAddress').style.display="none";
  document.getElementById('updateAddress').style.display="none";
  document.getElementById('deleteAddress').style.display="none";
    document.getElementById('insertContact').style.display="none";
      document.getElementById('updateContact').style.display="initial";
      document.getElementById('deleteContact').style.display="none";
}
function deleteContact(){
  document.getElementById('updateSex').style.display="none";
  document.getElementById('insertSex').style.display="none";
  document.getElementById('deleteSex').style.display="none";
  document.getElementById('insertCountry').style.display="none";
  document.getElementById('updateCountry').style.display="none";
  document.getElementById('deleteCountry').style.display="none";
  document.getElementById('insertCity').style.display="none";
  document.getElementById('updateCity').style.display="none";
  document.getElementById('deleteCity').style.display="none";
  document.getElementById('insertAddress').style.display="none";
  document.getElementById('updateAddress').style.display="none";
  document.getElementById('deleteAddress').style.display="none";
    document.getElementById('insertContact').style.display="none";
      document.getElementById('updateContact').style.display="none";
      document.getElementById('deleteContact').style.display="initial";
}
function displayErrors(){
  document.getElementById('err').style.display="initial";
}
function abort(){
removeForms();
}
